// ============================================================
// BASE DE DATOS: Carreras EMS 2024-2025
// Generado a partir del Excel oficial de la SEP
// Carreras con pendiente:true requieren contenido ODS
// Subsistemas validos: BTED, DGETI, DGETAyCM, CECyTE, CONALEP
// ============================================================
const db = [
    {
        nombre: "Administracion",
        subsistemas: ["BTED", "CECyTE", "DGETAyCM", "DGETI", "CONALEP"],
        s: "000000",
        sec: "Por definir",
        m: "Por definir",
        a: ["Actividad pendiente de definir.", "Actividad pendiente de definir.", "Actividad pendiente de definir.", "Actividad pendiente de definir.", "Actividad pendiente de definir."],
        h: "Por definir",
        o1: "0", o1_t: "Por definir",
        o2: "0", o2_t: "Por definir",
        i: "Por definir",
        d: "Contenido pendiente de desarrollo.",
        orientacion: "Instructor(a): Contenido pendiente de desarrollo.",
        pendiente: true
    },
    {
        nombre: "Mecatronica",
        subsistemas: ["CECyTE", "DGETAyCM", "DGETI", "CONALEP"],
        s: "000000",
        sec: "Por definir",
        m: "Por definir",
        a: ["Actividad pendiente de definir.", "Actividad pendiente de definir.", "Actividad pendiente de definir.", "Actividad pendiente de definir.", "Actividad pendiente de definir."],
        h: "Por definir",
        o1: "0", o1_t: "Por definir",
        o2: "0", o2_t: "Por definir",
        i: "Por definir",
        d: "Contenido pendiente de desarrollo.",
        orientacion: "Instructor(a): Contenido pendiente de desarrollo.",
        pendiente: true
    },
    {
        nombre: "Contabilidad",
        subsistemas: ["CECyTE", "DGETAyCM", "DGETI", "CONALEP"],
        s: "000000",
        sec: "Por definir",
        m: "Por definir",
        a: ["Actividad pendiente de definir.", "Actividad pendiente de definir.", "Actividad pendiente de definir.", "Actividad pendiente de definir.", "Actividad pendiente de definir."],
        h: "Por definir",
        o1: "0", o1_t: "Por definir",
        o2: "0", o2_t: "Por definir",
        i: "Por definir",
        d: "Contenido pendiente de desarrollo.",
        orientacion: "Instructor(a): Contenido pendiente de desarrollo.",
        pendiente: true
    },
    {
        nombre: "Electromecanica Industrial",
        subsistemas: ["CECyTE", "DGETAyCM", "DGETI", "CONALEP"],
        s: "333249",
        sec: "Fabricacion de maquinaria y equipo para otras industrias",
        m: "Modulo II: Mantiene sistemas de transmision de potencia",
        a: ["Optimizacion de sistemas de transmision para reducir las perdidas de energia por friccion o desalineacion.", "Mantenimiento preventivo de motores electricos para asegurar su operacion en el punto de maxima eficiencia.", "Gestion responsable de lubricantes y grasas industriales para evitar derrames y contaminacion del suelo.", "Instalacion de variadores de frecuencia para el control de velocidad y ahorro energetico en procesos industriales.", "Implementacion de protocolos de bloqueo y etiquetado (LOTO) para garantizar la seguridad del personal de mantenimiento."],
        h: "Eficiencia Operativa y Seguridad Industrial",
        o1: "9", o1_t: "Industria, Innovacion e Infraestructura",
        o2: "7", o2_t: "Energia Asequible y No Contaminante",
        i: "Reduccion de paros no programados y ahorro energetico",
        d: "El tecnico electromecanico es el guardian de la continuidad operativa bajo estandares de alta eficiencia energetica.",
        orientacion: "Instructor(a): Evalue la destreza del alumno en el diagnostico de fallas que causan consumos electricos anormales."
    },
    {
        nombre: "Informatica",
        subsistemas: ["CECyTE", "DGETAyCM", "DGETI", "CONALEP"],
        s: "000000",
        sec: "Por definir",
        m: "Por definir",
        a: ["Actividad pendiente de definir.", "Actividad pendiente de definir.", "Actividad pendiente de definir.", "Actividad pendiente de definir.", "Actividad pendiente de definir."],
        h: "Por definir",
        o1: "0", o1_t: "Por definir",
        o2: "0", o2_t: "Por definir",
        i: "Por definir",
        d: "Contenido pendiente de desarrollo.",
        orientacion: "Instructor(a): Contenido pendiente de desarrollo.",
        pendiente: true
    },
    {
        nombre: "Mantenimiento de Sistemas Electronicos",
        subsistemas: ["CECyTE", "DGETAyCM", "DGETI", "CONALEP"],
        s: "000000",
        sec: "Por definir",
        m: "Por definir",
        a: ["Actividad pendiente de definir.", "Actividad pendiente de definir.", "Actividad pendiente de definir.", "Actividad pendiente de definir.", "Actividad pendiente de definir."],
        h: "Por definir",
        o1: "0", o1_t: "Por definir",
        o2: "0", o2_t: "Por definir",
        i: "Por definir",
        d: "Contenido pendiente de desarrollo.",
        orientacion: "Instructor(a): Contenido pendiente de desarrollo.",
        pendiente: true
    },
    {
        nombre: "Alimentos y Bebidas",
        subsistemas: ["CECyTE", "DGETAyCM", "DGETI", "CONALEP"],
        s: "722511",
        sec: "Servicios de preparacion de alimentos y bebidas",
        m: "Modulo II: Prepara alimentos de acuerdo al recetario base",
        a: ["Aplicacion de la tecnica 'Pequenas Porciones, Gran Valor' para reducir el desperdicio de alimentos en el plato del comensal.", "Aprovechamiento de insumos locales y de temporada provenientes de cadenas cortas agropecuarias.", "Separacion estricta de residuos organicos para su aprovechamiento en procesos de compostaje o biogas.", "Uso eficiente de equipos de refrigeracion y coccion para minimizar el gasto de gas y electricidad.", "Gestion responsable de aceites vegetales usados para evitar la contaminacion de mantos freaticos y drenajes."],
        h: "Gastronomia Sostenible y Soberania Alimentaria",
        o1: "12", o1_t: "Produccion y Consumo Responsables",
        o2: "2", o2_t: "Hambre Cero",
        i: "Kilogramos de residuos organicos recuperados para compostaje",
        d: "La tecnica en alimentos impacta en la reduccion de residuos y fortalece la economia de los productores locales.",
        orientacion: "Instructor(a): Oriente al alumno en la gestion de inventarios 'PEPS' y en la importancia de consumir lo local."
    },
    {
        nombre: "Administracion de emprendimientos",
        subsistemas: ["BTED", "CECyTE", "DGETAyCM", "DGETI"],
        s: "000000",
        sec: "Por definir",
        m: "Por definir",
        a: ["Actividad pendiente de definir.", "Actividad pendiente de definir.", "Actividad pendiente de definir.", "Actividad pendiente de definir.", "Actividad pendiente de definir."],
        h: "Por definir",
        o1: "0", o1_t: "Por definir",
        o2: "0", o2_t: "Por definir",
        i: "Por definir",
        d: "Contenido pendiente de desarrollo.",
        orientacion: "Instructor(a): Contenido pendiente de desarrollo.",
        pendiente: true
    },
    {
        nombre: "Fuentes alternas de energia",
        subsistemas: ["CECyTE", "DGETAyCM", "DGETI", "CONALEP"],
        s: "000000",
        sec: "Por definir",
        m: "Por definir",
        a: ["Actividad pendiente de definir.", "Actividad pendiente de definir.", "Actividad pendiente de definir.", "Actividad pendiente de definir.", "Actividad pendiente de definir."],
        h: "Por definir",
        o1: "0", o1_t: "Por definir",
        o2: "0", o2_t: "Por definir",
        i: "Por definir",
        d: "Contenido pendiente de desarrollo.",
        orientacion: "Instructor(a): Contenido pendiente de desarrollo.",
        pendiente: true
    },
    {
        nombre: "Refrigeracion y Climatizacion",
        subsistemas: ["CECyTE", "DGETI", "CONALEP"],
        s: "333412",
        sec: "Fabricacion de equipo de refrigeracion industrial y comercial",
        m: "Modulo IV: Mantiene sistemas de refrigeracion industrial",
        a: ["Sustitucion de refrigerantes con alto potencial de calentamiento global por alternativas ecologicas y naturales.", "Optimizacion de la eficiencia energetica en sistemas de refrigeracion de plantas procesadoras de alimentos.", "Recuperacion, reciclaje y regeneracion de gases refrigerantes para evitar su liberacion a la atmosfera.", "Implementacion de sistemas de monitoreo remoto para detectar fugas de gas de manera inmediata.", "Mantenimiento preventivo a camaras frias para reducir el desperdicio de energia y la perdida de productos perecederos."],
        h: "Gestion Atmosferica y Cadena de Frio",
        o1: "13", o1_t: "Accion por el Clima",
        o2: "7", o2_t: "Energia Asequible y No Contaminante",
        i: "Toneladas de CO2 equivalente evitadas mediante gestion de gases",
        d: "El tecnico en refrigeracion es un guardian de la capa de ozono y un pilar para la seguridad alimentaria nacional.",
        orientacion: "Instructor(a): Verifique el uso obligatorio de la bomba de vacio y la unidad recuperadora durante las practicas de mantenimiento."
    },
    {
        nombre: "Autotronica",
        subsistemas: ["CECyTE", "CONALEP"],
        s: "811111",
        sec: "Reparacion y mantenimiento de automoviles y camiones",
        m: "Modulo IV: Diagnostica el estado de los sistemas de encendido y control de emisiones",
        a: ["Afinacion tecnica de motores para reducir la emision de gases contaminantes (CO2 y NOx) a la atmosfera.", "Diagnostico electronico del sistema de inyeccion para optimizar el rendimiento de combustible.", "Gestion responsable de aceites usados, filtros y baterias para evitar la contaminacion de suelos.", "Mantenimiento de sistemas de frenado regenerativo en vehiculos hibridos y electricos.", "Implementacion de protocolos de seguridad en el taller para prevenir riesgos laborales y accidentes."],
        h: "Movilidad Sostenible y Eficiencia Energetica",
        o1: "13", o1_t: "Accion por el Clima",
        o2: "9", o2_t: "Industria, Innovacion e Infraestructura",
        i: "Reduccion de emisiones verificada post-mantenimiento",
        d: "El tecnico automotriz es clave para asegurar una movilidad que respete los limites ambientales y proteja la salud urbana.",
        orientacion: "Instructor(a): Verifique que el alumno utilice correctamente el analizador de gases y comprenda el impacto de una mala combustion en el ODS 13."
    },
    {
        nombre: "Administracion de Recursos Humanos",
        subsistemas: ["CECyTE", "DGETAyCM", "DGETI"],
        s: "561110",
        sec: "Servicios de apoyo a los negocios",
        m: "Modulo IV: Controla los procesos de capacitacion y desarrollo del capital humano",
        a: ["Diseno de planes de formacion tecnica que incluyan competencias en sostenibilidad y responsabilidad social.", "Implementacion de politicas de igualdad salarial y no discriminacion en los procesos de promocion interna.", "Evaluacion de riesgos psicosociales (NOM-035) para garantizar un entorno de trabajo seguro y decente.", "Promocion de la diversidad e inclusion de grupos vulnerables en la plantilla laboral de la empresa.", "Gestion de programas de bienestar que fomenten el equilibrio entre la vida laboral y familiar."],
        h: "Capital Humano y Trabajo Decente",
        o1: "8", o1_t: "Trabajo Decente y Crecimiento Economico",
        o2: "10", o2_t: "Reduccion de las Desigualdades",
        i: "Indice de satisfaccion laboral y equidad de genero",
        d: "Gestionar el talento con etica es la base para construir organizaciones productivas que no dejen a nadie atras.",
        orientacion: "Instructor(a): Fomente en el alumno el uso de indicadores de inclusion y el analisis de la brecha salarial de genero."
    },
    {
        nombre: "Electronica",
        subsistemas: ["CECyTE", "DGETAyCM", "DGETI"],
        s: "334410",
        sec: "Fabricacion de componentes electronicos",
        m: "Modulo II: Implementa sistemas de control de baja potencia",
        a: ["Diseno de circuitos electronicos de bajo consumo (Low Power Design) para extender la vida de las baterias.", "Implementacion de sensores de luz y movimiento para la automatizacion de edificios inteligentes y ahorro energetico.", "Reparacion y mantenimiento de tarjetas electronicas para combatir la obsolescencia programada y reducir la basura electronica.", "Uso de soldadura libre de plomo para reducir el impacto toxico de los componentes al final de su vida util.", "Desarrollo de prototipos de monitoreo ambiental (calidad del aire/agua) basados en hardware abierto."],
        h: "Eco-diseno y Eficiencia Energetica",
        o1: "9", o1_t: "Industria, Innovacion e Infraestructura",
        o2: "7", o2_t: "Energia Asequible y No Contaminante",
        i: "Reduccion de consumo en standby de los dispositivos",
        d: "La electronica es el cerebro de la transicion energetica; sin control inteligente no hay ahorro de recursos.",
        orientacion: "Instructor(a): Evalue la capacidad del alumno para proponer mejoras en la eficiencia de una fuente de alimentacion."
    },
    {
        nombre: "Logistica",
        subsistemas: ["CECyTE", "DGETAyCM", "DGETI"],
        s: "488512",
        sec: "Servicios de mensajeria y paqueteria",
        m: "Modulo IV: Organiza el transporte de mercancias",
        a: ["Diseno de rutas de transporte optimizadas (Software de ruteo) para reducir el consumo de diesel y la huella de carbono.", "Implementacion de estrategias de 'ultima milla' mediante vehiculos electricos o transporte no motorizado.", "Supervision del embalaje sostenible utilizando materiales biodegradables y reduciendo el uso de plasticos de embalaje.", "Gestion de la logistica inversa para el retorno de envases y embalajes, promoviendo la economia circular.", "Auditoria de proveedores de transporte para asegurar el cumplimiento de normas de mantenimiento y bajas emisiones."],
        h: "Suministro Etico y Descarbonizacion",
        o1: "12", o1_t: "Produccion y Consumo Responsables",
        o2: "13", o2_t: "Accion por el Clima",
        i: "Reduccion de kilometros recorridos por unidad de carga",
        d: "La logistica tecnica es el puente hacia un consumo consciente; optimizar el movimiento es salvar energia.",
        orientacion: "Instructor(a): Verifique que el alumno calcule el ahorro de emisiones al consolidar cargas y optimizar rutas."
    },
    {
        nombre: "Preparacion de alimentos y bebidas",
        subsistemas: ["CECyTE", "DGETAyCM", "DGETI"],
        s: "722511",
        sec: "Servicios de preparacion de alimentos y bebidas",
        m: "Modulo II: Prepara alimentos de acuerdo al recetario base",
        a: ["Aplicacion de la tecnica 'Pequenas Porciones, Gran Valor' para reducir el desperdicio de alimentos en el plato del comensal.", "Aprovechamiento de insumos locales y de temporada provenientes de cadenas cortas agropecuarias.", "Separacion estricta de residuos organicos para su aprovechamiento en procesos de compostaje o biogas.", "Uso eficiente de equipos de refrigeracion y coccion para minimizar el gasto de gas y electricidad.", "Gestion responsable de aceites vegetales usados para evitar la contaminacion de mantos freaticos y drenajes."],
        h: "Gastronomia Sostenible y Soberania Alimentaria",
        o1: "12", o1_t: "Produccion y Consumo Responsables",
        o2: "2", o2_t: "Hambre Cero",
        i: "Kilogramos de residuos organicos recuperados para compostaje",
        d: "La tecnica en alimentos impacta en la reduccion de residuos y fortalece la economia de los productores locales.",
        orientacion: "Instructor(a): Oriente al alumno en la gestion de inventarios 'PEPS' y en la importancia de consumir lo local."
    },
    {
        nombre: "Programacion",
        subsistemas: ["CECyTE", "DGETAyCM", "DGETI"],
        s: "000000",
        sec: "Por definir",
        m: "Por definir",
        a: ["Actividad pendiente de definir.", "Actividad pendiente de definir.", "Actividad pendiente de definir.", "Actividad pendiente de definir.", "Actividad pendiente de definir."],
        h: "Por definir",
        o1: "0", o1_t: "Por definir",
        o2: "0", o2_t: "Por definir",
        i: "Por definir",
        d: "Contenido pendiente de desarrollo.",
        orientacion: "Instructor(a): Contenido pendiente de desarrollo.",
        pendiente: true
    },
    {
        nombre: "Mantenimiento industrial",
        subsistemas: ["CECyTE", "DGETAyCM", "DGETI"],
        s: "811311",
        sec: "Reparacion y mantenimiento de maquinaria y equipo industrial",
        m: "Modulo III: Mantiene sistemas neumaticos e hidraulicos",
        a: ["Deteccion y sellado de fugas en lineas de aire comprimido para reducir el desperdicio de energia electrica en compresores.", "Implementacion de planes de recuperacion y filtrado de aceites hidraulicos para evitar su desecho prematuro.", "Sustitucion de componentes neumaticos por versiones de bajo consumo de aire (eficiencia fluidica).", "Mantenimiento preventivo de valvulas y actuadores para garantizar la precision operativa y reducir mermas de produccion.", "Aplicacion de protocolos de seguridad para el manejo de energias peligrosas (bloqueo y etiquetado)."],
        h: "Mantenimiento Preventivo y Ahorro Energetico",
        o1: "9", o1_t: "Industria, Innovacion e Infraestructura",
        o2: "12", o2_t: "Produccion y Consumo Responsables",
        i: "Reduccion de m3 de aire comprimido desperdiciado",
        d: "El mantenimiento tecnico asegura que la industria opere con el minimo impacto ambiental y el maximo aprovechamiento de recursos.",
        orientacion: "Instructor(a): Verifique que el alumno identifique el costo energetico de una fuga de aire y proponga medidas de correccion inmediata."
    },
    {
        nombre: "Produccion industrial de alimentos",
        subsistemas: ["CECyTE", "DGETAyCM", "DGETI"],
        s: "311999",
        sec: "Industrias alimentarias",
        m: "Modulo II: Realiza los procesos de transformacion de productos lacteos",
        a: ["Optimizacion del uso de agua en los procesos de limpieza y sanitizacion de equipos industriales (Sistemas CIP).", "Tratamiento de suero lacteo para evitar su vertido en drenajes, transformandolo en productos de valor agregado.", "Implementacion de controles de temperatura precisos para evitar el desperdicio de materia prima por descomposicion.", "Uso de tecnologias de empaque al vacio o atmosfera modificada para extender la vida util del producto de forma natural.", "Supervision del cumplimiento de la NOM-251-SSA1 para garantizar alimentos inocuos y evitar mermas sanitarias."],
        h: "Eco-Procesamiento y Seguridad Alimentaria",
        o1: "2", o1_t: "Hambre Cero",
        o2: "12", o2_t: "Produccion y Consumo Responsables",
        i: "Porcentaje de suero lacteo recuperado o procesado",
        d: "La industria alimentaria tecnica debe cerrar sus ciclos, convirtiendo subproductos en recursos para combatir el hambre.",
        orientacion: "Instructor(a): Evalue la propuesta del alumno para el manejo del suero de leche, evitando su impacto ambiental."
    },
    {
        nombre: "Construccion",
        subsistemas: ["DGETI", "CONALEP"],
        s: "541310",
        sec: "Servicios de arquitectura",
        m: "Modulo III: Realiza planos arquitectonicos y constructivos con software",
        a: ["Integracion de sistemas de captacion de agua pluvial y tratamiento de aguas grises en el diseno de viviendas.", "Uso de software para el calculo de asoleamiento y ventilacion natural, reduciendo la necesidad de aire acondicionado.", "Seleccion de materiales de construccion locales y sustentables para reducir la huella de carbono por transporte.", "Diseno de espacios bajo principios de accesibilidad universal para garantizar la inclusion de personas con discapacidad.", "Planificacion de areas verdes y superficies permeables para mitigar el efecto de isla de calor urbana."],
        h: "Urbanismo Sostenible y Construccion Verde",
        o1: "11", o1_t: "Ciudades y Comunidades Sostenibles",
        o2: "9", o2_t: "Industria, Innovacion e Infraestructura",
        i: "Metros cuadrados de diseno con criterios bio-climaticos",
        d: "La arquitectura del futuro debe construir habitats que regeneren el entorno en lugar de solo consumirlo.",
        orientacion: "Instructor(a): Verifique que los planos incluyan detalles tecnicos de ecotecnias o accesibilidad universal."
    },
    {
        nombre: "Ciencia de Datos e Inteligencia Artificial",
        subsistemas: ["CECyTE", "DGETI", "CONALEP"],
        s: "000000",
        sec: "Por definir",
        m: "Por definir",
        a: ["Actividad pendiente de definir.", "Actividad pendiente de definir.", "Actividad pendiente de definir.", "Actividad pendiente de definir.", "Actividad pendiente de definir."],
        h: "Por definir",
        o1: "0", o1_t: "Por definir",
        o2: "0", o2_t: "Por definir",
        i: "Por definir",
        d: "Contenido pendiente de desarrollo.",
        orientacion: "Instructor(a): Contenido pendiente de desarrollo.",
        pendiente: true
    },
    {
        nombre: "Ciencia de datos e informacion",
        subsistemas: ["CECyTE", "DGETI"],
        s: "000000",
        sec: "Por definir",
        m: "Por definir",
        a: ["Actividad pendiente de definir.", "Actividad pendiente de definir.", "Actividad pendiente de definir.", "Actividad pendiente de definir.", "Actividad pendiente de definir."],
        h: "Por definir",
        o1: "0", o1_t: "Por definir",
        o2: "0", o2_t: "Por definir",
        i: "Por definir",
        d: "Contenido pendiente de desarrollo.",
        orientacion: "Instructor(a): Contenido pendiente de desarrollo.",
        pendiente: true
    },
    {
        nombre: "Electromecanica",
        subsistemas: ["CECyTE", "DGETI"],
        s: "000000",
        sec: "Por definir",
        m: "Por definir",
        a: ["Actividad pendiente de definir.", "Actividad pendiente de definir.", "Actividad pendiente de definir.", "Actividad pendiente de definir.", "Actividad pendiente de definir."],
        h: "Por definir",
        o1: "0", o1_t: "Por definir",
        o2: "0", o2_t: "Por definir",
        i: "Por definir",
        d: "Contenido pendiente de desarrollo.",
        orientacion: "Instructor(a): Contenido pendiente de desarrollo.",
        pendiente: true
    },
    {
        nombre: "Inteligencia artificial",
        subsistemas: ["CECyTE", "DGETI"],
        s: "000000",
        sec: "Por definir",
        m: "Por definir",
        a: ["Actividad pendiente de definir.", "Actividad pendiente de definir.", "Actividad pendiente de definir.", "Actividad pendiente de definir.", "Actividad pendiente de definir."],
        h: "Por definir",
        o1: "0", o1_t: "Por definir",
        o2: "0", o2_t: "Por definir",
        i: "Por definir",
        d: "Contenido pendiente de desarrollo.",
        orientacion: "Instructor(a): Contenido pendiente de desarrollo.",
        pendiente: true
    },
    {
        nombre: "Refrigeracion y aire acondicionado",
        subsistemas: ["CECyTE", "DGETI"],
        s: "000000",
        sec: "Por definir",
        m: "Por definir",
        a: ["Actividad pendiente de definir.", "Actividad pendiente de definir.", "Actividad pendiente de definir.", "Actividad pendiente de definir.", "Actividad pendiente de definir."],
        h: "Por definir",
        o1: "0", o1_t: "Por definir",
        o2: "0", o2_t: "Por definir",
        i: "Por definir",
        d: "Contenido pendiente de desarrollo.",
        orientacion: "Instructor(a): Contenido pendiente de desarrollo.",
        pendiente: true
    },
    {
        nombre: "Servicios de hospedaje",
        subsistemas: ["CECyTE", "DGETI"],
        s: "000000",
        sec: "Por definir",
        m: "Por definir",
        a: ["Actividad pendiente de definir.", "Actividad pendiente de definir.", "Actividad pendiente de definir.", "Actividad pendiente de definir.", "Actividad pendiente de definir."],
        h: "Por definir",
        o1: "0", o1_t: "Por definir",
        o2: "0", o2_t: "Por definir",
        i: "Por definir",
        d: "Contenido pendiente de desarrollo.",
        orientacion: "Instructor(a): Contenido pendiente de desarrollo.",
        pendiente: true
    },
    {
        nombre: "Turismo",
        subsistemas: ["DGETI", "CONALEP"],
        s: "000000",
        sec: "Por definir",
        m: "Por definir",
        a: ["Actividad pendiente de definir.", "Actividad pendiente de definir.", "Actividad pendiente de definir.", "Actividad pendiente de definir.", "Actividad pendiente de definir."],
        h: "Por definir",
        o1: "0", o1_t: "Por definir",
        o2: "0", o2_t: "Por definir",
        i: "Por definir",
        d: "Contenido pendiente de desarrollo.",
        orientacion: "Instructor(a): Contenido pendiente de desarrollo.",
        pendiente: true
    },
    {
        nombre: "Control de Calidad",
        subsistemas: ["CONALEP"],
        s: "541990",
        sec: "Servicios profesionales, cientificos y tecnicos",
        m: "Modulo II: Realiza pruebas fisicas y quimicas a materiales",
        a: ["Aplicacion de control estadistico de procesos para reducir la generacion de productos defectuosos y desperdicio de materia prima.", "Implementacion de tecnicas de metrologia dimensional para asegurar la precision y evitar el re-trabajo industrial.", "Supervision del cumplimiento de normativas ambientales y de seguridad en los procesos de manufactura.", "Uso de herramientas de mejora continua (Lean Six Sigma) para optimizar el uso de recursos energeticos y materiales.", "Gestion de la trazabilidad del producto para garantizar la seguridad del consumidor y la responsabilidad corporativa."],
        h: "Excelencia Operativa y Cero Desperdicio",
        o1: "9", o1_t: "Industria, Innovacion e Infraestructura",
        o2: "12", o2_t: "Produccion y Consumo Responsables",
        i: "Reduccion del indice de scrap (desperdicio) por lote",
        d: "El tecnico en control de calidad asegura que la eficiencia y la sostenibilidad se cumplan desde la primera fase de produccion.",
        orientacion: "Instructor(a): Evalue la destreza del alumno en el uso de instrumentos de medicion y la interpretacion de graficas de control."
    },
    {
        nombre: "Escenotecnia",
        subsistemas: ["CONALEP"],
        s: "000000",
        sec: "Por definir",
        m: "Por definir",
        a: ["Actividad pendiente de definir.", "Actividad pendiente de definir.", "Actividad pendiente de definir.", "Actividad pendiente de definir.", "Actividad pendiente de definir."],
        h: "Por definir",
        o1: "0", o1_t: "Por definir",
        o2: "0", o2_t: "Por definir",
        i: "Por definir",
        d: "Contenido pendiente de desarrollo.",
        orientacion: "Instructor(a): Contenido pendiente de desarrollo.",
        pendiente: true
    },
    {
        nombre: "Industria del Vestido",
        subsistemas: ["CONALEP"],
        s: "000000",
        sec: "Por definir",
        m: "Por definir",
        a: ["Actividad pendiente de definir.", "Actividad pendiente de definir.", "Actividad pendiente de definir.", "Actividad pendiente de definir.", "Actividad pendiente de definir."],
        h: "Por definir",
        o1: "0", o1_t: "Por definir",
        o2: "0", o2_t: "Por definir",
        i: "Por definir",
        d: "Contenido pendiente de desarrollo.",
        orientacion: "Instructor(a): Contenido pendiente de desarrollo.",
        pendiente: true
    },
    {
        nombre: "Maquinas Herramienta",
        subsistemas: ["CONALEP"],
        s: "332710",
        sec: "Maquinado de piezas industriales y fabricacion de tornillos",
        m: "Modulo IV: Maquina piezas por Control Numerico Computarizado (CNC)",
        a: ["Programacion eficiente de trayectorias de corte para reducir el tiempo de maquinado y el gasto energetico.", "Uso de fluidos de corte (refrigerantes) biodegradables y sistemas de filtracion para prolongar su vida util.", "Gestion y clasificacion de virutas metalicas para su reintegracion en la cadena de reciclaje siderurgico.", "Aplicacion de metrologia de alta precision para evitar el re-trabajo y el desperdicio de piezas defectuosas.", "Mantenimiento predictivo de los husillos y guias para asegurar la maxima eficiencia operativa del equipo."],
        h: "Manufactura de Alta Precision y Cero Desperdicio",
        o1: "9", o1_t: "Industria, Innovacion e Infraestructura",
        o2: "12", o2_t: "Produccion y Consumo Responsables",
        i: "Reduccion de piezas rechazadas (merma cero)",
        d: "La precision tecnica en el maquinado es sinonimo de eficiencia; producir bien a la primera es una accion sostenible.",
        orientacion: "Instructor(a): Oriente al alumno en el calculo de avances y velocidades para maximizar la vida util de las herramientas de corte."
    },
    {
        nombre: "Produccion y Transformacion de Productos Acuicolas",
        subsistemas: ["DGETAyCM", "CONALEP"],
        s: "000000",
        sec: "Por definir",
        m: "Por definir",
        a: ["Actividad pendiente de definir.", "Actividad pendiente de definir.", "Actividad pendiente de definir.", "Actividad pendiente de definir.", "Actividad pendiente de definir."],
        h: "Por definir",
        o1: "0", o1_t: "Por definir",
        o2: "0", o2_t: "Por definir",
        i: "Por definir",
        d: "Contenido pendiente de desarrollo.",
        orientacion: "Instructor(a): Contenido pendiente de desarrollo.",
        pendiente: true
    },
    {
        nombre: "Quimica Industrial",
        subsistemas: ["CONALEP"],
        s: "325999",
        sec: "Fabricacion de otros productos quimicos",
        m: "Modulo III: Realiza analisis quimicos industriales",
        a: ["Optimizacion de procesos quimicos para reducir la generacion de subproductos toxicos o residuos peligrosos.", "Implementacion de sistemas de recuperacion de solventes mediante destilacion para su reutilizacion en planta.", "Monitoreo de emisiones atmosfericas y efluentes liquidos para asegurar el cumplimiento de las normas ambientales (SEMARNAT).", "Sustitucion de reactivos convencionales por alternativas de 'Quimica Verde' con menor impacto ambiental.", "Gestion estricta de la hoja de seguridad de materiales (MSDS) para prevenir riesgos quimicos y accidentes laborales."],
        h: "Procesos Quimicos Sostenibles y Seguridad",
        o1: "12", o1_t: "Produccion y Consumo Responsables",
        o2: "9", o2_t: "Industria, Innovacion e Infraestructura",
        i: "Reduccion de residuos quimicos peligrosos por lote de produccion",
        d: "La quimica industrial tecnica busca transformar la materia de forma eficiente, minimizando la huella toxica en el entorno.",
        orientacion: "Instructor(a): Verifique que el alumno domine el pesaje analitico y el manejo de residuos quimicos de acuerdo a su compatibilidad."
    },
    {
        nombre: "Seguridad e Higiene y Proteccion Civil",
        subsistemas: ["CONALEP"],
        s: "000000",
        sec: "Por definir",
        m: "Por definir",
        a: ["Actividad pendiente de definir.", "Actividad pendiente de definir.", "Actividad pendiente de definir.", "Actividad pendiente de definir.", "Actividad pendiente de definir."],
        h: "Por definir",
        o1: "0", o1_t: "Por definir",
        o2: "0", o2_t: "Por definir",
        i: "Por definir",
        d: "Contenido pendiente de desarrollo.",
        orientacion: "Instructor(a): Contenido pendiente de desarrollo.",
        pendiente: true
    },
    {
        nombre: "Laministeria y Recubrimiento de las Aeronaves",
        subsistemas: ["CONALEP"],
        s: "000000",
        sec: "Por definir",
        m: "Por definir",
        a: ["Actividad pendiente de definir.", "Actividad pendiente de definir.", "Actividad pendiente de definir.", "Actividad pendiente de definir.", "Actividad pendiente de definir."],
        h: "Por definir",
        o1: "0", o1_t: "Por definir",
        o2: "0", o2_t: "Por definir",
        i: "Por definir",
        d: "Contenido pendiente de desarrollo.",
        orientacion: "Instructor(a): Contenido pendiente de desarrollo.",
        pendiente: true
    },
    {
        nombre: "Mantenimiento Automotriz",
        subsistemas: ["CONALEP"],
        s: "811111",
        sec: "Reparacion y mantenimiento de automoviles y camiones",
        m: "Modulo IV: Diagnostica el estado de los sistemas de encendido y control de emisiones",
        a: ["Afinacion tecnica de motores para reducir la emision de gases contaminantes (CO2 y NOx) a la atmosfera.", "Diagnostico electronico del sistema de inyeccion para optimizar el rendimiento de combustible.", "Gestion responsable de aceites usados, filtros y baterias para evitar la contaminacion de suelos.", "Mantenimiento de sistemas de frenado regenerativo en vehiculos hibridos y electricos.", "Implementacion de protocolos de seguridad en el taller para prevenir riesgos laborales y accidentes."],
        h: "Movilidad Sostenible y Eficiencia Energetica",
        o1: "13", o1_t: "Accion por el Clima",
        o2: "9", o2_t: "Industria, Innovacion e Infraestructura",
        i: "Reduccion de emisiones verificada post-mantenimiento",
        d: "El tecnico automotriz es clave para asegurar una movilidad que respete los limites ambientales y proteja la salud urbana.",
        orientacion: "Instructor(a): Verifique que el alumno utilice correctamente el analizador de gases y comprenda el impacto de una mala combustion en el ODS 13."
    },
    {
        nombre: "Mantenimiento de Motores y Planeadores",
        subsistemas: ["CONALEP"],
        s: "488110",
        sec: "Servicios relacionados con el transporte aereo",
        m: "Modulo II: Mantiene los sistemas electricos y electronicos de las aeronaves",
        a: ["Ejecucion de inspecciones rigurosas para asegurar la maxima eficiencia de combustion en motores aeronauticos.", "Gestion estricta de residuos peligrosos (aceites y solventes) segun la normativa aeronautica internacional.", "Implementacion de tecnicas de mantenimiento predictivo para extender la vida util de los componentes estructurales.", "Uso de materiales compuestos avanzados que reducen el peso de la aeronave y el consumo de combustible.", "Optimizacion de los procesos de limpieza de motores para reducir el arrastre aerodinamico y las emisiones."],
        h: "Seguridad Aeronautica y Eficiencia de Combustible",
        o1: "9", o1_t: "Industria, Innovacion e Infraestructura",
        o2: "12", o2_t: "Produccion y Consumo Responsables",
        i: "Reduccion de consumo de turbosina por milla volada mediante mantenimiento optimo",
        d: "La precision en el mantenimiento aeronautico garantiza la seguridad humana y minimiza el impacto ambiental del transporte aereo.",
        orientacion: "Instructor(a): Supervise el manejo de bitacoras de mantenimiento y la correcta disposicion final de lubricantes usados."
    },
    {
        nombre: "Expresion Grafica Digital",
        subsistemas: ["CONALEP"],
        s: "000000",
        sec: "Por definir",
        m: "Por definir",
        a: ["Actividad pendiente de definir.", "Actividad pendiente de definir.", "Actividad pendiente de definir.", "Actividad pendiente de definir.", "Actividad pendiente de definir."],
        h: "Por definir",
        o1: "0", o1_t: "Por definir",
        o2: "0", o2_t: "Por definir",
        i: "Por definir",
        d: "Contenido pendiente de desarrollo.",
        orientacion: "Instructor(a): Contenido pendiente de desarrollo.",
        pendiente: true
    },
    {
        nombre: "Soporte y Mantenimiento de Equipo de Computo",
        subsistemas: ["CONALEP"],
        s: "000000",
        sec: "Por definir",
        m: "Por definir",
        a: ["Actividad pendiente de definir.", "Actividad pendiente de definir.", "Actividad pendiente de definir.", "Actividad pendiente de definir.", "Actividad pendiente de definir."],
        h: "Por definir",
        o1: "0", o1_t: "Por definir",
        o2: "0", o2_t: "Por definir",
        i: "Por definir",
        d: "Contenido pendiente de desarrollo.",
        orientacion: "Instructor(a): Contenido pendiente de desarrollo.",
        pendiente: true
    },
    {
        nombre: "Telecomunicaciones",
        subsistemas: ["CONALEP"],
        s: "517311",
        sec: "Operadores de telecomunicaciones alambricas e inalambricas",
        m: "Modulo II: Instala y mantiene redes de telecomunicaciones",
        a: ["Instalacion de redes de fibra optica para maximizar la velocidad de transmision con menor consumo de energia.", "Configuracion de equipos de red con protocolos de ahorro energetico (Green IT) en horarios de baja demanda.", "Mantenimiento preventivo de estaciones base y antenas para reducir la basura electronica y extender la vida util del equipo.", "Implementacion de sistemas de alimentacion solar en repetidoras de zonas remotas para reducir la huella de carbono.", "Gestion responsable de cables y componentes electronicos obsoletos mediante programas de reciclaje tecnico."],
        h: "Conectividad Sostenible y Eficiencia Digital",
        o1: "9", o1_t: "Industria, Innovacion e Infraestructura",
        o2: "17", o2_t: "Alianzas para lograr los Objetivos",
        i: "Kilometros de red instalada con protocolos de eficiencia energetica",
        d: "Las telecomunicaciones tecnicas son el sistema nervioso de la sociedad moderna; su eficiencia es clave para cerrar la brecha digital.",
        orientacion: "Instructor(a): Verifique que el alumno domine el proceso de fusion de fibra optica y el uso de equipos de medicion como el OTDR."
    },
    {
        nombre: "Electricidad Industrial",
        subsistemas: ["CONALEP"],
        s: "000000",
        sec: "Por definir",
        m: "Por definir",
        a: ["Actividad pendiente de definir.", "Actividad pendiente de definir.", "Actividad pendiente de definir.", "Actividad pendiente de definir.", "Actividad pendiente de definir."],
        h: "Por definir",
        o1: "0", o1_t: "Por definir",
        o2: "0", o2_t: "Por definir",
        i: "Por definir",
        d: "Contenido pendiente de desarrollo.",
        orientacion: "Instructor(a): Contenido pendiente de desarrollo.",
        pendiente: true
    },
    {
        nombre: "Sistemas Electronicos de Aviacion",
        subsistemas: ["CONALEP"],
        s: "000000",
        sec: "Por definir",
        m: "Por definir",
        a: ["Actividad pendiente de definir.", "Actividad pendiente de definir.", "Actividad pendiente de definir.", "Actividad pendiente de definir.", "Actividad pendiente de definir."],
        h: "Por definir",
        o1: "0", o1_t: "Por definir",
        o2: "0", o2_t: "Por definir",
        i: "Por definir",
        d: "Contenido pendiente de desarrollo.",
        orientacion: "Instructor(a): Contenido pendiente de desarrollo.",
        pendiente: true
    },
    {
        nombre: "Enfermeria General",
        subsistemas: ["CONALEP"],
        s: "000000",
        sec: "Por definir",
        m: "Por definir",
        a: ["Actividad pendiente de definir.", "Actividad pendiente de definir.", "Actividad pendiente de definir.", "Actividad pendiente de definir.", "Actividad pendiente de definir."],
        h: "Por definir",
        o1: "0", o1_t: "Por definir",
        o2: "0", o2_t: "Por definir",
        i: "Por definir",
        d: "Contenido pendiente de desarrollo.",
        orientacion: "Instructor(a): Contenido pendiente de desarrollo.",
        pendiente: true
    },
    {
        nombre: "Optometria",
        subsistemas: ["CONALEP"],
        s: "000000",
        sec: "Por definir",
        m: "Por definir",
        a: ["Actividad pendiente de definir.", "Actividad pendiente de definir.", "Actividad pendiente de definir.", "Actividad pendiente de definir.", "Actividad pendiente de definir."],
        h: "Por definir",
        o1: "0", o1_t: "Por definir",
        o2: "0", o2_t: "Por definir",
        i: "Por definir",
        d: "Contenido pendiente de desarrollo.",
        orientacion: "Instructor(a): Contenido pendiente de desarrollo.",
        pendiente: true
    },
    {
        nombre: "Terapia Respiratoria",
        subsistemas: ["CONALEP"],
        s: "000000",
        sec: "Por definir",
        m: "Por definir",
        a: ["Actividad pendiente de definir.", "Actividad pendiente de definir.", "Actividad pendiente de definir.", "Actividad pendiente de definir.", "Actividad pendiente de definir."],
        h: "Por definir",
        o1: "0", o1_t: "Por definir",
        o2: "0", o2_t: "Por definir",
        i: "Por definir",
        d: "Contenido pendiente de desarrollo.",
        orientacion: "Instructor(a): Contenido pendiente de desarrollo.",
        pendiente: true
    },
    {
        nombre: "Asistente Directivo",
        subsistemas: ["CONALEP"],
        s: "561110",
        sec: "Servicios de apoyo a los negocios",
        m: "Modulo II: Gestiona documentacion y comunicacion oficial",
        a: ["Implementacion de sistemas de archivo digital para alcanzar el objetivo de 'Oficina Cero Papel'.", "Gestion eficiente de la agenda ejecutiva priorizando reuniones virtuales para reducir la huella de carbono por viajes.", "Uso de herramientas ofimaticas en la nube para el trabajo colaborativo y la reduccion de insumos fisicos.", "Aplicacion de normas de etica y confidencialidad en el manejo de la informacion institucional.", "Promocion de compras verdes y suministros de oficina con certificaciones ecologicas."],
        h: "Gestion Administrativa Sostenible",
        o1: "12", o1_t: "Produccion y Consumo Responsables",
        o2: "8", o2_t: "Trabajo Decente y Crecimiento Economico",
        i: "Porcentaje de reduccion en el consumo de suministros de oficina",
        d: "El asistente directivo moderno coordina la eficiencia operativa desde un enfoque de responsabilidad ambiental y etica.",
        orientacion: "Instructor(a): Fomente en el alumno el uso de firmas digitales y protocolos de ciberseguridad para la proteccion de datos."
    },
    {
        nombre: "Atletismo",
        subsistemas: ["BTED"],
        s: "000000",
        sec: "Por definir",
        m: "Por definir",
        a: ["Actividad pendiente de definir.", "Actividad pendiente de definir.", "Actividad pendiente de definir.", "Actividad pendiente de definir.", "Actividad pendiente de definir."],
        h: "Por definir",
        o1: "0", o1_t: "Por definir",
        o2: "0", o2_t: "Por definir",
        i: "Por definir",
        d: "Contenido pendiente de desarrollo.",
        orientacion: "Instructor(a): Contenido pendiente de desarrollo.",
        pendiente: true
    },
    {
        nombre: "Beisbol",
        subsistemas: ["BTED"],
        s: "000000",
        sec: "Por definir",
        m: "Por definir",
        a: ["Actividad pendiente de definir.", "Actividad pendiente de definir.", "Actividad pendiente de definir.", "Actividad pendiente de definir.", "Actividad pendiente de definir."],
        h: "Por definir",
        o1: "0", o1_t: "Por definir",
        o2: "0", o2_t: "Por definir",
        i: "Por definir",
        d: "Contenido pendiente de desarrollo.",
        orientacion: "Instructor(a): Contenido pendiente de desarrollo.",
        pendiente: true
    },
    {
        nombre: "Boxeo",
        subsistemas: ["BTED"],
        s: "000000",
        sec: "Por definir",
        m: "Por definir",
        a: ["Actividad pendiente de definir.", "Actividad pendiente de definir.", "Actividad pendiente de definir.", "Actividad pendiente de definir.", "Actividad pendiente de definir."],
        h: "Por definir",
        o1: "0", o1_t: "Por definir",
        o2: "0", o2_t: "Por definir",
        i: "Por definir",
        d: "Contenido pendiente de desarrollo.",
        orientacion: "Instructor(a): Contenido pendiente de desarrollo.",
        pendiente: true
    },
    {
        nombre: "Agropecuario",
        subsistemas: ["DGETAyCM"],
        s: "000000",
        sec: "Por definir",
        m: "Por definir",
        a: ["Actividad pendiente de definir.", "Actividad pendiente de definir.", "Actividad pendiente de definir.", "Actividad pendiente de definir.", "Actividad pendiente de definir."],
        h: "Por definir",
        o1: "0", o1_t: "Por definir",
        o2: "0", o2_t: "Por definir",
        i: "Por definir",
        d: "Contenido pendiente de desarrollo.",
        orientacion: "Instructor(a): Contenido pendiente de desarrollo.",
        pendiente: true
    },
    {
        nombre: "Fisioterapia del ejercicio fisico",
        subsistemas: ["BTED"],
        s: "000000",
        sec: "Por definir",
        m: "Por definir",
        a: ["Actividad pendiente de definir.", "Actividad pendiente de definir.", "Actividad pendiente de definir.", "Actividad pendiente de definir.", "Actividad pendiente de definir."],
        h: "Por definir",
        o1: "0", o1_t: "Por definir",
        o2: "0", o2_t: "Por definir",
        i: "Por definir",
        d: "Contenido pendiente de desarrollo.",
        orientacion: "Instructor(a): Contenido pendiente de desarrollo.",
        pendiente: true
    },
    {
        nombre: "Agroindustrias",
        subsistemas: ["DGETAyCM"],
        s: "000000",
        sec: "Por definir",
        m: "Por definir",
        a: ["Actividad pendiente de definir.", "Actividad pendiente de definir.", "Actividad pendiente de definir.", "Actividad pendiente de definir.", "Actividad pendiente de definir."],
        h: "Por definir",
        o1: "0", o1_t: "Por definir",
        o2: "0", o2_t: "Por definir",
        i: "Por definir",
        d: "Contenido pendiente de desarrollo.",
        orientacion: "Instructor(a): Contenido pendiente de desarrollo.",
        pendiente: true
    },
    {
        nombre: "Mecanica naval",
        subsistemas: ["DGETAyCM"],
        s: "811312",
        sec: "Reparacion y mantenimiento de maquinaria y equipo pesado",
        m: "Modulo III: Mantiene sistemas de propulsion marina",
        a: ["Ajuste tecnico de motores fuera de borda e intraborda para optimizar el consumo de combustible y reducir emisiones.", "Mantenimiento preventivo de sistemas de transmision marina para evitar fugas de lubricantes al ecosistema oceanico.", "Reparacion de sistemas de gobierno y propulsion para garantizar la seguridad de la navegacion en alta mar.", "Implementacion de protocolos de limpieza de motores que eviten la dispersion de especies invasoras en el agua de lastre.", "Gestion responsable de baterias y componentes electronicos marinos para su reciclaje tecnico."],
        h: "Mantenimiento Maritimo y Proteccion Oceanica",
        o1: "14", o1_t: "Vida Submarina",
        o2: "9", o2_t: "Industria, Innovacion e Infraestructura",
        i: "Reduccion de consumo de combustible por hora de navegacion mediante ajuste tecnico",
        d: "El mecanico naval tecnico es el garante de que la flota opere de forma segura y respetuosa con la biodiversidad de nuestros mares.",
        orientacion: "Instructor(a): Verifique que el alumno aplique las normas de seguridad maritima y el manejo correcto de hidrocarburos en el taller."
    },
    {
        nombre: "Gericultura",
        subsistemas: ["DGETI"],
        s: "624120",
        sec: "Servicios de centros de atencion para personas con discapacidad y ancianos",
        m: "Modulo IV: Auxilia al adulto mayor en las actividades de la vida diaria",
        a: ["Diseno de planes de activacion fisica y mental para promover el envejecimiento activo y saludable.", "Implementacion de tecnicas de movilizacion segura que prevengan lesiones y mejoren la calidad de vida del adulto mayor.", "Acompanamiento emocional y social para combatir el aislamiento y la depresion en la tercera edad.", "Administracion responsable de cuidados paliativos y preventivos bajo supervision medica.", "Promocion de entornos accesibles y seguros que respeten la dignidad y autonomia de las personas mayores."],
        h: "Cuidado Digno y Envejecimiento Saludable",
        o1: "3", o1_t: "Salud y Bienestar",
        o2: "10", o2_t: "Reduccion de las Desigualdades",
        i: "Mejora en el indice de autonomia funcional de las personas atendidas",
        d: "La gericultura tecnica responde al reto demografico, asegurando que el envejecimiento sea una etapa de vida digna y protegida.",
        orientacion: "Instructor(a): Evalue la sensibilidad y paciencia del alumno, asi como su dominio de las tecnicas de primeros auxilios geriatricos."
    },
    {
        nombre: "Agrotecnologia",
        subsistemas: ["CONALEP"],
        s: "115110",
        sec: "Servicios relacionados con la agricultura",
        m: "Modulo IV: Emplea tecnologias de agricultura de precision",
        a: ["Uso de drones para el monitoreo de salud de cultivos, permitiendo la aplicacion focalizada de insumos (tasa variable).", "Instalacion de estaciones meteorologicas y sensores IoT para predecir plagas y optimizar calendarios de siembra.", "Analisis de imagenes multiespectrales para determinar deficiencias nutricionales sin sobrefertilizar el suelo.", "Gestion de grandes volumenes de datos (Big Data) para mejorar la toma de decisiones en la unidad de produccion.", "Implementacion de sistemas de trazabilidad digital desde la siembra hasta la cosecha para garantizar inocuidad."],
        h: "Agricultura Digital y Precision Climatica",
        o1: "2", o1_t: "Hambre Cero",
        o2: "9", o2_t: "Industria, Innovacion e Infraestructura",
        i: "Reduccion del uso de agroquimicos por hectarea mediante aplicacion dirigida",
        d: "La agrotecnologia es la evolucion digital del campo, permitiendo producir mas alimentos con una huella ambiental minima.",
        orientacion: "Instructor(a): Evalue la capacidad del alumno para interpretar mapas de rendimiento y operar software de SIG (Sistemas de Informacion Geografica)."
    },
    {
        nombre: "Artes Graficas",
        subsistemas: ["CONALEP"],
        s: "323119",
        sec: "Industrias de las artes graficas",
        m: "Modulo III: Produce salidas graficas en diversos sistemas de impresion",
        a: ["Uso de tintas con base vegetal y solventes de bajo impacto ambiental para reducir emisiones de COV.", "Optimizacion del sustrato (papel/carton) mediante software de imposicion para reducir el sobrante de papel.", "Implementacion de protocolos de reciclaje de placas metalicas y residuos quimicos de pre-prensa.", "Fomento del uso de papeles certificados FSC o de fibras alternativas para proteger la biodiversidad forestal.", "Mantenimiento preventivo de los equipos de impresion para asegurar la maxima eficiencia energetica por tiraje."],
        h: "Comunicacion Grafica Sustentable",
        o1: "12", o1_t: "Produccion y Consumo Responsables",
        o2: "15", o2_t: "Vida de Ecosistemas Terrestres",
        i: "Porcentaje de reduccion de merma de papel por orden de trabajo",
        d: "La industria grafica moderna debe evolucionar hacia procesos limpios que reduzcan el impacto quimico y forestal.",
        orientacion: "Instructor(a): Evalue la capacidad del alumno para proponer el uso de materiales reciclables en proyectos de empaque."
    },
    {
        nombre: "Conservacion del Medio Ambiente",
        subsistemas: ["CONALEP"],
        s: "000000",
        sec: "Por definir",
        m: "Por definir",
        a: ["Actividad pendiente de definir.", "Actividad pendiente de definir.", "Actividad pendiente de definir.", "Actividad pendiente de definir.", "Actividad pendiente de definir."],
        h: "Por definir",
        o1: "0", o1_t: "Por definir",
        o2: "0", o2_t: "Por definir",
        i: "Por definir",
        d: "Contenido pendiente de desarrollo.",
        orientacion: "Instructor(a): Contenido pendiente de desarrollo.",
        pendiente: true
    },
    {
        nombre: "Curtiduria",
        subsistemas: ["CONALEP"],
        s: "000000",
        sec: "Por definir",
        m: "Por definir",
        a: ["Actividad pendiente de definir.", "Actividad pendiente de definir.", "Actividad pendiente de definir.", "Actividad pendiente de definir.", "Actividad pendiente de definir."],
        h: "Por definir",
        o1: "0", o1_t: "Por definir",
        o2: "0", o2_t: "Por definir",
        i: "Por definir",
        d: "Contenido pendiente de desarrollo.",
        orientacion: "Instructor(a): Contenido pendiente de desarrollo.",
        pendiente: true
    },
    {
        nombre: "Exploracion y Produccion Petrolera",
        subsistemas: ["CONALEP"],
        s: "000000",
        sec: "Por definir",
        m: "Por definir",
        a: ["Actividad pendiente de definir.", "Actividad pendiente de definir.", "Actividad pendiente de definir.", "Actividad pendiente de definir.", "Actividad pendiente de definir."],
        h: "Por definir",
        o1: "0", o1_t: "Por definir",
        o2: "0", o2_t: "Por definir",
        i: "Por definir",
        d: "Contenido pendiente de desarrollo.",
        orientacion: "Instructor(a): Contenido pendiente de desarrollo.",
        pendiente: true
    },
    {
        nombre: "Industria Automotriz",
        subsistemas: ["CONALEP"],
        s: "000000",
        sec: "Por definir",
        m: "Por definir",
        a: ["Actividad pendiente de definir.", "Actividad pendiente de definir.", "Actividad pendiente de definir.", "Actividad pendiente de definir.", "Actividad pendiente de definir."],
        h: "Por definir",
        o1: "0", o1_t: "Por definir",
        o2: "0", o2_t: "Por definir",
        i: "Por definir",
        d: "Contenido pendiente de desarrollo.",
        orientacion: "Instructor(a): Contenido pendiente de desarrollo.",
        pendiente: true
    },
    {
        nombre: "Metalmecanica",
        subsistemas: ["CONALEP"],
        s: "000000",
        sec: "Por definir",
        m: "Por definir",
        a: ["Actividad pendiente de definir.", "Actividad pendiente de definir.", "Actividad pendiente de definir.", "Actividad pendiente de definir.", "Actividad pendiente de definir."],
        h: "Por definir",
        o1: "0", o1_t: "Por definir",
        o2: "0", o2_t: "Por definir",
        i: "Por definir",
        d: "Contenido pendiente de desarrollo.",
        orientacion: "Instructor(a): Contenido pendiente de desarrollo.",
        pendiente: true
    },
    {
        nombre: "Metalurgia",
        subsistemas: ["CONALEP"],
        s: "331111",
        sec: "Industria basica del hierro y del acero",
        m: "Modulo III: Controla los procesos de fundicion y moldeo",
        a: ["Optimizacion de la carga termica en hornos para reducir el consumo de combustible y las emisiones de CO2.", "Implementacion de tecnicas de reciclaje de chatarra ferrosa y no ferrosa para reintegrarlas al ciclo productivo.", "Monitoreo y filtrado de polvos y gases de combustion para minimizar el impacto ambiental de la fundicion.", "Uso de arenas de moldeo recuperadas para reducir la extraccion de aridos naturales.", "Gestion segura de escorias metalicas para su posible aprovechamiento en la industria de la construccion."],
        h: "Metalurgia Circular y Eficiencia Termica",
        o1: "9", o1_t: "Industria, Innovacion e Infraestructura",
        o2: "12", o2_t: "Produccion y Consumo Responsables",
        i: "Toneladas de metal reciclado procesadas",
        d: "La metalurgia tecnica es el corazon de la infraestructura; hacerla eficiente es clave para una industria sostenible.",
        orientacion: "Instructor(a): Evalue la capacidad del alumno para realizar balances de materia y energia en procesos de fundicion."
    },
    {
        nombre: "Minero Metalurgista",
        subsistemas: ["CONALEP"],
        s: "000000",
        sec: "Por definir",
        m: "Por definir",
        a: ["Actividad pendiente de definir.", "Actividad pendiente de definir.", "Actividad pendiente de definir.", "Actividad pendiente de definir.", "Actividad pendiente de definir."],
        h: "Por definir",
        o1: "0", o1_t: "Por definir",
        o2: "0", o2_t: "Por definir",
        i: "Por definir",
        d: "Contenido pendiente de desarrollo.",
        orientacion: "Instructor(a): Contenido pendiente de desarrollo.",
        pendiente: true
    },
    {
        nombre: "Plasticos",
        subsistemas: ["CONALEP"],
        s: "326199",
        sec: "Fabricacion de otros productos de plastico",
        m: "Modulo III: Controla la transformacion de plasticos por inyeccion",
        a: ["Configuracion de parametros de maquina para minimizar el consumo de energia electrica por ciclo de produccion.", "Integracion de material recuperado (post-industrial) en el proceso de inyeccion para fomentar la economia circular.", "Optimizacion del diseno de moldes para reducir el desperdicio de material (coladas y rebabas).", "Sustitucion progresiva de polimeros virgenes por bioplasticos o materiales compostables.", "Implementacion de sistemas de enfriamiento de agua en circuito cerrado para evitar el desperdicio del recurso hidrico."],
        h: "Economia Circular y Manufactura Responsable",
        o1: "12", o1_t: "Produccion y Consumo Responsables",
        o2: "9", o2_t: "Industria, Innovacion e Infraestructura",
        i: "Porcentaje de material reciclado integrado en la produccion",
        d: "La industria del plastico debe transformarse hacia modelos de ciclo cerrado donde el residuo se convierta en recurso.",
        orientacion: "Instructor(a): Fomente en el alumno la busqueda de soluciones para reducir el 'scrap' (desperdicio) en los arranques de maquina."
    },
    {
        nombre: "Procesamiento Industrial de Alimentos",
        subsistemas: ["CONALEP"],
        s: "311999",
        sec: "Industrias alimentarias",
        m: "Modulo II: Realiza los procesos de transformacion de productos lacteos",
        a: ["Optimizacion del uso de agua en los procesos de limpieza y sanitizacion de equipos industriales (Sistemas CIP).", "Tratamiento de suero lacteo para evitar su vertido en drenajes, transformandolo en productos de valor agregado.", "Implementacion de controles de temperatura precisos para evitar el desperdicio de materia prima por descomposicion.", "Uso de tecnologias de empaque al vacio o atmosfera modificada para extender la vida util del producto de forma natural.", "Supervision del cumplimiento de la NOM-251-SSA1 para garantizar alimentos inocuos y evitar mermas sanitarias."],
        h: "Eco-Procesamiento y Seguridad Alimentaria",
        o1: "2", o1_t: "Hambre Cero",
        o2: "12", o2_t: "Produccion y Consumo Responsables",
        i: "Porcentaje de suero lacteo recuperado o procesado",
        d: "La industria alimentaria tecnica debe cerrar sus ciclos, convirtiendo subproductos en recursos para combatir el hambre.",
        orientacion: "Instructor(a): Evalue la propuesta del alumno para el manejo del suero de leche, evitando su impacto ambiental."
    },
    {
        nombre: "Produccion de Calzado",
        subsistemas: ["CONALEP"],
        s: "000000",
        sec: "Por definir",
        m: "Por definir",
        a: ["Actividad pendiente de definir.", "Actividad pendiente de definir.", "Actividad pendiente de definir.", "Actividad pendiente de definir.", "Actividad pendiente de definir."],
        h: "Por definir",
        o1: "0", o1_t: "Por definir",
        o2: "0", o2_t: "Por definir",
        i: "Por definir",
        d: "Contenido pendiente de desarrollo.",
        orientacion: "Instructor(a): Contenido pendiente de desarrollo.",
        pendiente: true
    },
    {
        nombre: "Productividad Industrial",
        subsistemas: ["CONALEP"],
        s: "000000",
        sec: "Por definir",
        m: "Por definir",
        a: ["Actividad pendiente de definir.", "Actividad pendiente de definir.", "Actividad pendiente de definir.", "Actividad pendiente de definir.", "Actividad pendiente de definir."],
        h: "Por definir",
        o1: "0", o1_t: "Por definir",
        o2: "0", o2_t: "Por definir",
        i: "Por definir",
        d: "Contenido pendiente de desarrollo.",
        orientacion: "Instructor(a): Contenido pendiente de desarrollo.",
        pendiente: true
    },
    {
        nombre: "Soldaduras Industriales",
        subsistemas: ["CONALEP"],
        s: "332310",
        sec: "Fabricacion de estructuras metalicas",
        m: "Modulo III: Suelda piezas metalicas con proceso SMAW",
        a: ["Optimizacion del uso de electrodos y materiales de aporte para reducir el desperdicio metalico.", "Implementacion de sistemas de extraccion de humos y ventilacion para proteger la salud respiratoria del soldador.", "Uso de equipos de proteccion personal (EPP) normados para garantizar un entorno de trabajo seguro y decente.", "Gestion responsable de las colillas de electrodos y residuos de escoria para su disposicion final tecnica.", "Mantenimiento preventivo de las fuentes de poder (maquinas de soldar) para asegurar la eficiencia energetica del arco."],
        h: "Seguridad Industrial y Eficiencia en Procesos",
        o1: "8", o1_t: "Trabajo Decente y Crecimiento Economico",
        o2: "9", o2_t: "Industria, Innovacion e Infraestructura",
        i: "Reduccion de tasa de accidentes y desperdicio de insumos",
        d: "La soldadura tecnica es la union de la infraestructura nacional; hacerla con seguridad y eficiencia es construir futuro.",
        orientacion: "Instructor(a): Verifique que el alumno aplique las normas de seguridad AWS y supervise el manejo de residuos de fundente."
    },
    {
        nombre: "Textil",
        subsistemas: ["CONALEP"],
        s: "000000",
        sec: "Por definir",
        m: "Por definir",
        a: ["Actividad pendiente de definir.", "Actividad pendiente de definir.", "Actividad pendiente de definir.", "Actividad pendiente de definir.", "Actividad pendiente de definir."],
        h: "Por definir",
        o1: "0", o1_t: "Por definir",
        o2: "0", o2_t: "Por definir",
        i: "Por definir",
        d: "Contenido pendiente de desarrollo.",
        orientacion: "Instructor(a): Contenido pendiente de desarrollo.",
        pendiente: true
    },
    {
        nombre: "Mantenimiento de Sistemas Automaticos",
        subsistemas: ["CONALEP"],
        s: "000000",
        sec: "Por definir",
        m: "Por definir",
        a: ["Actividad pendiente de definir.", "Actividad pendiente de definir.", "Actividad pendiente de definir.", "Actividad pendiente de definir.", "Actividad pendiente de definir."],
        h: "Por definir",
        o1: "0", o1_t: "Por definir",
        o2: "0", o2_t: "Por definir",
        i: "Por definir",
        d: "Contenido pendiente de desarrollo.",
        orientacion: "Instructor(a): Contenido pendiente de desarrollo.",
        pendiente: true
    },
    {
        nombre: "Motores a Diesel",
        subsistemas: ["CONALEP"],
        s: "000000",
        sec: "Por definir",
        m: "Por definir",
        a: ["Actividad pendiente de definir.", "Actividad pendiente de definir.", "Actividad pendiente de definir.", "Actividad pendiente de definir.", "Actividad pendiente de definir."],
        h: "Por definir",
        o1: "0", o1_t: "Por definir",
        o2: "0", o2_t: "Por definir",
        i: "Por definir",
        d: "Contenido pendiente de desarrollo.",
        orientacion: "Instructor(a): Contenido pendiente de desarrollo.",
        pendiente: true
    },
    {
        nombre: "Operacion y Mantenimiento de Maquinaria Pesada",
        subsistemas: ["CONALEP"],
        s: "000000",
        sec: "Por definir",
        m: "Por definir",
        a: ["Actividad pendiente de definir.", "Actividad pendiente de definir.", "Actividad pendiente de definir.", "Actividad pendiente de definir.", "Actividad pendiente de definir."],
        h: "Por definir",
        o1: "0", o1_t: "Por definir",
        o2: "0", o2_t: "Por definir",
        i: "Por definir",
        d: "Contenido pendiente de desarrollo.",
        orientacion: "Instructor(a): Contenido pendiente de desarrollo.",
        pendiente: true
    },
    {
        nombre: "Autotransporte",
        subsistemas: ["CONALEP"],
        s: "000000",
        sec: "Por definir",
        m: "Por definir",
        a: ["Actividad pendiente de definir.", "Actividad pendiente de definir.", "Actividad pendiente de definir.", "Actividad pendiente de definir.", "Actividad pendiente de definir."],
        h: "Por definir",
        o1: "0", o1_t: "Por definir",
        o2: "0", o2_t: "Por definir",
        i: "Por definir",
        d: "Contenido pendiente de desarrollo.",
        orientacion: "Instructor(a): Contenido pendiente de desarrollo.",
        pendiente: true
    },
    {
        nombre: "Pilotaje de Drones",
        subsistemas: ["CONALEP"],
        s: "000000",
        sec: "Por definir",
        m: "Por definir",
        a: ["Actividad pendiente de definir.", "Actividad pendiente de definir.", "Actividad pendiente de definir.", "Actividad pendiente de definir.", "Actividad pendiente de definir."],
        h: "Por definir",
        o1: "0", o1_t: "Por definir",
        o2: "0", o2_t: "Por definir",
        i: "Por definir",
        d: "Contenido pendiente de desarrollo.",
        orientacion: "Instructor(a): Contenido pendiente de desarrollo.",
        pendiente: true
    },
    {
        nombre: "Transporte Ferroviario",
        subsistemas: ["CONALEP"],
        s: "000000",
        sec: "Por definir",
        m: "Por definir",
        a: ["Actividad pendiente de definir.", "Actividad pendiente de definir.", "Actividad pendiente de definir.", "Actividad pendiente de definir.", "Actividad pendiente de definir."],
        h: "Por definir",
        o1: "0", o1_t: "Por definir",
        o2: "0", o2_t: "Por definir",
        i: "Por definir",
        d: "Contenido pendiente de desarrollo.",
        orientacion: "Instructor(a): Contenido pendiente de desarrollo.",
        pendiente: true
    },
    {
        nombre: "Asistente y Protesista Dental",
        subsistemas: ["CONALEP"],
        s: "000000",
        sec: "Por definir",
        m: "Por definir",
        a: ["Actividad pendiente de definir.", "Actividad pendiente de definir.", "Actividad pendiente de definir.", "Actividad pendiente de definir.", "Actividad pendiente de definir."],
        h: "Por definir",
        o1: "0", o1_t: "Por definir",
        o2: "0", o2_t: "Por definir",
        i: "Por definir",
        d: "Contenido pendiente de desarrollo.",
        orientacion: "Instructor(a): Contenido pendiente de desarrollo.",
        pendiente: true
    },
    {
        nombre: "Enfermeria Comunitaria",
        subsistemas: ["CONALEP"],
        s: "000000",
        sec: "Por definir",
        m: "Por definir",
        a: ["Actividad pendiente de definir.", "Actividad pendiente de definir.", "Actividad pendiente de definir.", "Actividad pendiente de definir.", "Actividad pendiente de definir."],
        h: "Por definir",
        o1: "0", o1_t: "Por definir",
        o2: "0", o2_t: "Por definir",
        i: "Por definir",
        d: "Contenido pendiente de desarrollo.",
        orientacion: "Instructor(a): Contenido pendiente de desarrollo.",
        pendiente: true
    },
    {
        nombre: "Fonoaudiologia",
        subsistemas: ["CONALEP"],
        s: "000000",
        sec: "Por definir",
        m: "Por definir",
        a: ["Actividad pendiente de definir.", "Actividad pendiente de definir.", "Actividad pendiente de definir.", "Actividad pendiente de definir.", "Actividad pendiente de definir."],
        h: "Por definir",
        o1: "0", o1_t: "Por definir",
        o2: "0", o2_t: "Por definir",
        i: "Por definir",
        d: "Contenido pendiente de desarrollo.",
        orientacion: "Instructor(a): Contenido pendiente de desarrollo.",
        pendiente: true
    },
    {
        nombre: "Laboratorio Clinico",
        subsistemas: ["CONALEP"],
        s: "621511",
        sec: "Laboratorios medicos y de diagnostico",
        m: "Modulo III: Realiza analisis hematologicos de serie roja",
        a: ["Gestion estricta de Residuos Peligrosos Biologico-Infecciosos (RPBI) para prevenir la contaminacion del suelo y mantos freaticos.", "Uso eficiente de reactivos mediante tecnicas de microescala para reducir la generacion de desechos quimicos.", "Promocion de la cultura de prevencion de enfermedades cronicas para reducir la carga sobre los servicios de salud publica.", "Implementacion de protocolos de bioseguridad que garanticen la salud y el bienestar del personal y los pacientes.", "Digitalizacion de resultados clinicos para eliminar el uso de papel y plasticos en la entrega de diagnosticos."],
        h: "Salud Publica y Gestion de Residuos",
        o1: "3", o1_t: "Salud y Bienestar",
        o2: "6", o2_t: "Agua Limpia y Saneamiento",
        i: "Kilogramos de RPBI gestionados correctamente",
        d: "El laboratorio clinico es la primera linea de defensa para el bienestar social y la proteccion ambiental contra patogenos.",
        orientacion: "Instructor(a): Verifique que el alumno domine la NOM-087-ECOL-SSA1 sobre el manejo de residuos infecciosos."
    },
    {
        nombre: "Nutricion y Dietetica",
        subsistemas: ["CONALEP"],
        s: "000000",
        sec: "Por definir",
        m: "Por definir",
        a: ["Actividad pendiente de definir.", "Actividad pendiente de definir.", "Actividad pendiente de definir.", "Actividad pendiente de definir.", "Actividad pendiente de definir."],
        h: "Por definir",
        o1: "0", o1_t: "Por definir",
        o2: "0", o2_t: "Por definir",
        i: "Por definir",
        d: "Contenido pendiente de desarrollo.",
        orientacion: "Instructor(a): Contenido pendiente de desarrollo.",
        pendiente: true
    },
    {
        nombre: "Radiologia e Imagen",
        subsistemas: ["CONALEP"],
        s: "000000",
        sec: "Por definir",
        m: "Por definir",
        a: ["Actividad pendiente de definir.", "Actividad pendiente de definir.", "Actividad pendiente de definir.", "Actividad pendiente de definir.", "Actividad pendiente de definir."],
        h: "Por definir",
        o1: "0", o1_t: "Por definir",
        o2: "0", o2_t: "Por definir",
        i: "Por definir",
        d: "Contenido pendiente de desarrollo.",
        orientacion: "Instructor(a): Contenido pendiente de desarrollo.",
        pendiente: true
    },
    {
        nombre: "Radioterapia",
        subsistemas: ["CONALEP"],
        s: "000000",
        sec: "Por definir",
        m: "Por definir",
        a: ["Actividad pendiente de definir.", "Actividad pendiente de definir.", "Actividad pendiente de definir.", "Actividad pendiente de definir.", "Actividad pendiente de definir."],
        h: "Por definir",
        o1: "0", o1_t: "Por definir",
        o2: "0", o2_t: "Por definir",
        i: "Por definir",
        d: "Contenido pendiente de desarrollo.",
        orientacion: "Instructor(a): Contenido pendiente de desarrollo.",
        pendiente: true
    },
    {
        nombre: "Salud Comunitaria",
        subsistemas: ["CONALEP"],
        s: "000000",
        sec: "Por definir",
        m: "Por definir",
        a: ["Actividad pendiente de definir.", "Actividad pendiente de definir.", "Actividad pendiente de definir.", "Actividad pendiente de definir.", "Actividad pendiente de definir."],
        h: "Por definir",
        o1: "0", o1_t: "Por definir",
        o2: "0", o2_t: "Por definir",
        i: "Por definir",
        d: "Contenido pendiente de desarrollo.",
        orientacion: "Instructor(a): Contenido pendiente de desarrollo.",
        pendiente: true
    },
    {
        nombre: "Terapia Fisica",
        subsistemas: ["CONALEP"],
        s: "000000",
        sec: "Por definir",
        m: "Por definir",
        a: ["Actividad pendiente de definir.", "Actividad pendiente de definir.", "Actividad pendiente de definir.", "Actividad pendiente de definir.", "Actividad pendiente de definir."],
        h: "Por definir",
        o1: "0", o1_t: "Por definir",
        o2: "0", o2_t: "Por definir",
        i: "Por definir",
        d: "Contenido pendiente de desarrollo.",
        orientacion: "Instructor(a): Contenido pendiente de desarrollo.",
        pendiente: true
    },
    {
        nombre: "Terapia Ocupacional",
        subsistemas: ["CONALEP"],
        s: "000000",
        sec: "Por definir",
        m: "Por definir",
        a: ["Actividad pendiente de definir.", "Actividad pendiente de definir.", "Actividad pendiente de definir.", "Actividad pendiente de definir.", "Actividad pendiente de definir."],
        h: "Por definir",
        o1: "0", o1_t: "Por definir",
        o2: "0", o2_t: "Por definir",
        i: "Por definir",
        d: "Contenido pendiente de desarrollo.",
        orientacion: "Instructor(a): Contenido pendiente de desarrollo.",
        pendiente: true
    },
    {
        nombre: "Asistente Bibliotecario",
        subsistemas: ["CONALEP"],
        s: "000000",
        sec: "Por definir",
        m: "Por definir",
        a: ["Actividad pendiente de definir.", "Actividad pendiente de definir.", "Actividad pendiente de definir.", "Actividad pendiente de definir.", "Actividad pendiente de definir."],
        h: "Por definir",
        o1: "0", o1_t: "Por definir",
        o2: "0", o2_t: "Por definir",
        i: "Por definir",
        d: "Contenido pendiente de desarrollo.",
        orientacion: "Instructor(a): Contenido pendiente de desarrollo.",
        pendiente: true
    }
];
